export default {
  PROJECTS_FETCH_START: 'PROJECTS_FETCH_START',
  PROJECTS_FETCH_SUCCESS: 'PROJECTS_FETCH_SUCCESS',
  PROJECTS_FETCH_FAIL: 'PROJECTS_FETCH_FAIL',
  PROJECTS_FETCH_ONE_START: 'PROJECTS_FETCH_ONE_START',
  PROJECTS_FETCH_ONE_SUCCESS: 'PROJECTS_FETCH_ONE_SUCCESS',
  PROJECTS_FETCH_ONE_FAIL: 'PROJECTS_FETCH_ONE_FAIL',
}
